# Generated by Django 2.0 on 2018-07-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180708_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('library_staff', 'Staff of library'),)},
        ),
    ]
